spring:
  docker:
    compose:
      enabled: false
#strava:
#  permission:
#    deleteActivity: false
#    writeComment: false
#    giveKudos: false
#    webhooksEndpoint: false
#    challengesEndpoint: false
#    beaconEndpoint: false